name: Build and Publish to ECR

on:
  workflow_dispatch:
#  push:
#    branches:
#      - main
#      - '*'

jobs:
  build-and-push-docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set Short SHA
      run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    - name: Build container image
      run: |
        docker build -t 2017-ppe:$SHORT_SHA -f Dockerfile .
        docker tag 2017-ppe:$SHORT_SHA 2017-ppe:latest
      env:
        SHORT_SHA: ${{ env.SHORT_SHA }}

    - name: Login to Amazon ECR
      if: github.ref == 'refs/heads/main'
      uses: aws-actions/amazon-ecr-login@v1
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'eu-west-1'

    - name: Push to Amazon ECR
      if: github.ref == 'refs/heads/main'
      run: |
        docker tag 2017-ppe:$SHORT_SHA $ECR_REGISTRY/$ECR_REPOSITORY:$SHORT_SHA
        docker tag 2017-ppe:$SHORT_SHA $ECR_REGISTRY/$ECR_REPOSITORY:latest
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$SHORT_SHA
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
      env:
        ECR_REGISTRY: 244530008913.dkr.ecr.eu-west-1.amazonaws.com
        ECR_REPOSITORY: kandidat2017
        SHORT_SHA: ${{ env.SHORT_SHA }}
        
  deploy-with-terraform:
    needs: build-and-push-docker
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    env:
      IMAGE: 244530008913.dkr.ecr.eu-west-1.amazonaws.com/kandidat2017:latest
      SERVICE_NAME: kandidat2017
    steps:
    - uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      working-directory: ./infra
      run: terraform init
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Terraform Plan
      working-directory: ./infra
      run: terraform plan
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        TF_VAR_image: ${{ env.IMAGE }}
        TF_VAR_service_name: ${{ env.SERVICE_NAME }}

    - name: Terraform Apply
      working-directory: ./infra
      run: terraform apply -auto-approve
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        TF_VAR_image: ${{ env.IMAGE }}
        TF_VAR_service_name: ${{ env.SERVICE_NAME }}